<?php

declare(strict_types=1);

namespace Pyz\Shared\OmsVisualizer;

class OmsVisualizerConstants
{
    public const string DEBUG_MODE = 'MERMAID:DEBUG_MODE';
    public const string MERMAID_GLOBAL_CONFIGURATION = 'MERMAID:MERMAID_GLOBAL_CONFIGURATION';
    public const string STATE_BORDER_WIDTH = 'MERMAID:STATE_BORDER_WIDTH';

    public const string INITIAL_STATE_BACKGROUND_COLOR = 'MERMAID:INITIAL_STATE_BACKGROUND_COLOR';
    public const string INITIAL_STATE_BORDER_COLOR = 'MERMAID:INITIAL_STATE_BORDER_COLOR';
    public const string INITIAL_STATE_FONT_COLOR = 'MERMAID:INITIAL_STATE_FONT_COLOR';

    public const string FINAL_STATE_BACKGROUND_COLOR = 'MERMAID:FINAL_STATE_BACKGROUND_COLOR';
    public const string FINAL_STATE_BORDER_COLOR = 'MERMAID:FINAL_STATE_BORDER_COLOR';
    public const string FINAL_STATE_FONT_COLOR = 'MERMAID:FINAL_STATE_FONT_COLOR';

    public const string FAILED_STATE_BACKGROUND_COLOR = 'MERMAID:FAILED_STATE_BACKGROUND_COLOR';
    public const string FAILED_STATE_BORDER_COLOR = 'MERMAID:FAILED_STATE_BORDER_COLOR';
    public const string FAILED_STATE_FONT_COLOR = 'MERMAID:FAILED_STATE_FONT_COLOR';

    public const string OBSOLETE_STATE_BACKGROUND_COLOR = 'MERMAID:OBSOLETE_STATE_BACKGROUND_COLOR';
    public const string OBSOLETE_STATE_BORDER_COLOR = 'MERMAID:OBSOLETE_STATE_BORDER_COLOR';
    public const string OBSOLETE_STATE_FONT_COLOR = 'MERMAID:OBSOLETE_STATE_FONT_COLOR';

    public const string NORMAL_STATE_BACKGROUND_COLOR = 'MERMAID:NORMAL_STATE_BACKGROUND_COLOR';
    public const string NORMAL_STATE_BORDER_COLOR = 'MERMAID:NORMAL_STATE_BORDER_COLOR';
    public const string NORMAL_STATE_FONT_COLOR = 'MERMAID:NORMAL_STATE_FONT_COLOR';

    public const string SUB_GRAPH_BACKGROUND_COLOR = 'MERMAID:SUB_GRAPH_BACKGROUND_COLOR';
    public const string SUB_GRAPH_BORDER_COLOR = 'MERMAID:SUB_GRAPH_BORDER_COLOR';

    public const string HAPPY_PATH_COLOR = 'MERMAID:HAPPY_PATH_COLOR';
    public const string OMS_CONFIGURATION_DIRECTORY = 'MERMAID:OMS_CONFIGURATION_DIRECTORY';
}
